### ISSUE TITLE
Other way to store API keys

### ISSUE THREAD

**Issue by mittalyashu** [austin-----/vscode-twitter#8]
I am using sync-settings and it uploading all the settings include API's to Github gist and since we are also using secret API key to make this extension work and we cannot share the secret API key publicly.

**Comment by austin-----** [comment]
A workaround is to store the secret API key in a workspace settings file instead, with the consequence that you can only use it in that workspace. I think the the “right” way to do it is for the sync software to allow a blacklist of settings from being uploaded.
